### ISSUE TITLE
Inquiry about nuget library

### ISSUE THREAD

**Issue by raymrdc** [Bayes-Price/TSAPI#30]
Will the Market Research standard Tsapi nuget library get published to nuget.org?

**Comment by tbrandwood** [comment]
Yep, definitely - I'm currently in the process of setting this up. Will let you know once it's in place..

**Comment by gfkeogh** [comment]
Yes! Urgent. Our Carbon import code was reading a very old copy of the SurveyMetadata class and died because it no longer matches the service response.

**Comment by tbrandwood** [comment]
FYI:- there is now an initial version of the TSAPI.Public library on nuget.org (Search for "TSAPI"). 
I think we've done this correctly, but I'd welcome comments/suggestions from anyone...

**Comment by gfkeogh** [comment]
The package is visible and we're using it, and the attributes and links all seem to work. You can close this issue.
